// Extracts the store list from the app's single source of truth (../stores.json,
// fetched at runtime by index.html) and writes a slim, bot-only module
// (stores.gen.js). This keeps ONE canonical dataset instead of a second
// hand-maintained copy, and it does NOT create a public raw-JSON endpoint: the
// output is bundled into the Worker at deploy time and git-ignored. Only the
// fields the bot needs are kept.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const jsonPath = fileURLToPath(new URL('../stores.json', import.meta.url));
const outPath = fileURLToPath(new URL('./stores.gen.js', import.meta.url));

const STORES = JSON.parse(readFileSync(jsonPath, 'utf8'));
if (!Array.isArray(STORES) || !STORES.length) throw new Error('stores.json did not parse to a non-empty array');

// Drop the watermark canary and keep only what the bot renders / reasons about.
const slim = STORES
  .filter((s) => !s.watermark)
  .map((s) => ({
    id: s.id,
    name: s.name,
    address: s.addressEn || s.address || '',
    pricing: s.pricing || 'item',
    restockDay: s.restockDay || null, // 'mon'..'fri' for fixed-schedule KG stores
    lat: s.lat,
    lng: s.lng,
    promo: s.promo || null, // optional paid promotion { tier, offer, until } — drives the sponsored slot
  }));

const banner = '// AUTO-GENERATED by build-data.mjs from ../index.html — do not edit by hand.\n';
writeFileSync(outPath, banner + 'export const STORES = ' + JSON.stringify(slim) + ';\n');

const withSchedule = slim.filter((s) => s.restockDay).length;
console.log(`Generated stores.gen.js — ${slim.length} stores (${withSchedule} with a fixed weekly restock day).`);
